version: '3.7'
services:
  web:
    container_name: backend
    build:
      context: ./library_site
      dockerfile: Dockerfile.prod
    command: gunicorn library_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    container_name: web
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
    - 80:80
    depends_on:
    - web
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432
volumes:
  postgres_data:
  static_volume:
  media_volume: