version: '3.7'
services:
  web:
    container_name: backend
    build:
      context: ./library_site
      dockerfile: Dockerfile.prod
    command: gunicorn library_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
    - 80:80
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=link49
      - POSTGRES_DB=django
    ports:
      - 5432:5432
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/var/lib/redis
  centrifugal:
    image: centrifugo/centrifugo
    command: centrifugo -c config.json
    restart: unless-stopped
    ports: 
    - "8001:8001"
    volumes: 
    - "./config:/centrifugo"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
volumes:
  postgres_data:
  esdata1:
  redis_data:
  static_volume:
