version: '3.7'
services:
  web:
    container_name: dev_backend
    build: ./library_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./library_site/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=link49
      - POSTGRES_DB=django
    ports:
      - 5432:5432
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/var/lib/redis
volumes:
  postgres_data:
  esdata1:
  redis_data:
