# Generated by Django 3.0 on 2021-12-11 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadS3_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files3',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
