# Generated by Django 3.0 on 2021-11-14 12:33

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Название книги')),
                ('publish_date', models.PositiveSmallIntegerField(verbose_name='Дата публикации')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=books.models.book_directory_path, verbose_name='Обложка')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.Author')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='genres.Genre')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
