# Generated by Django 3.0 on 2021-11-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('my_super_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type_name', models.CharField(choices=[('A', 'Action'), ('A', 'Adventure'), ('F', 'Fantasy'), ('H', 'Historical')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('my_super_pk', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=256)),
                ('book_description', models.TextField(max_length=4000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Author')),
                ('book_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Genre')),
            ],
        ),
    ]
