# Generated by Django 3.0 on 2021-12-11 20:56

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия автора')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=authors.models.author_directory_path, verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
